pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Taavi0192/SimpleApp.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('simple-name-app') {  // Change to the subdirectory containing the Dockerfile
                    sh 'docker build -t simple-name-app .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 3000:3000 simple-name-app'
            }
        }
    }
}
